/**
 * Build the MCPB bundle.
 *
 * Bundles `mcpb/src/server.ts` and everything it imports — including the shared
 * planning/tax engine under `lib/` — into a single `mcpb/server/index.js`, then
 * packs `mcpb/` into `dist/<name>-<version>.mcpb`.
 *
 * Bundling to one file (rather than shipping `node_modules`) keeps the archive
 * small, makes the install hermetic, and means the extension has no dependency
 * on the host's package manager. It works because the MCP tool graph is
 * deliberately free of Next.js and React — it is plain TypeScript over Supabase.
 *
 * Usage:
 *   node scripts/build-mcpb.mjs          # bundle + pack
 *   node scripts/build-mcpb.mjs --no-pack  # bundle only (fast iteration)
 */

import { build } from "esbuild"
import { spawnSync } from "node:child_process"
import { existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs"
import { dirname, join, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const BUNDLE_DIR = join(ROOT, "mcpb")
const OUT_DIR = join(BUNDLE_DIR, "server")
const OUT_FILE = join(OUT_DIR, "index.js")
const DIST_DIR = join(ROOT, "dist")

const pack = !process.argv.includes("--no-pack")

const manifest = JSON.parse(readFileSync(join(BUNDLE_DIR, "manifest.json"), "utf8"))

/** Run a command, echoing it, and fail the build if it does. */
function run(command, args, options = {}) {
  console.log(`$ ${command} ${args.join(" ")}`)
  const res = spawnSync(command, args, { stdio: "inherit", cwd: ROOT, ...options })
  if (res.status !== 0) {
    throw new Error(`${command} exited with ${res.status ?? res.signal}`)
  }
}

// ── 1. Icon ────────────────────────────────────────────────────────────────
if (!existsSync(join(BUNDLE_DIR, "manifest.json"))) {
  throw new Error("mcpb/manifest.json is missing")
}
if (!existsSync(join(BUNDLE_DIR, manifest.icon ?? "icon.png"))) {
  run(process.execPath, ["scripts/make-mcpb-icon.mjs"])
}

// ── 2. Bundle ──────────────────────────────────────────────────────────────
rmSync(OUT_DIR, { recursive: true, force: true })
mkdirSync(OUT_DIR, { recursive: true })

const result = await build({
  entryPoints: [join(BUNDLE_DIR, "src", "server.ts")],
  outfile: OUT_FILE,
  bundle: true,
  platform: "node",
  format: "esm",
  // MCPB's Node runtime floor; matches `compatibility.runtimes.node`.
  target: "node20",
  // Readable stack traces in the host's log matter more here than bytes: this
  // runs on one user's laptop, not in a hot serverless path.
  minify: false,
  keepNames: true,
  sourcemap: false,
  legalComments: "none",
  logLevel: "info",
  metafile: true,
  // Mirrors the `@/*` path alias in tsconfig.json.
  alias: { "@": ROOT },
  define: { "process.env.NODE_ENV": '"production"' },
  banner: {
    js:
      "// Generated by scripts/build-mcpb.mjs — do not edit.\n" +
      "// Source: mcpb/src/server.ts (+ the shared engine under lib/).\n" +
      // Some bundled CommonJS dependencies reach for `require`; ESM output has
      // no such binding, so provide one built from this module's own URL.
      'import { createRequire as __createRequire } from "node:module";\n' +
      "const require = __createRequire(import.meta.url);\n",
  },
})

// esbuild's `format: "esm"` output needs the directory marked as ESM, since the
// manifest's entry point is `.js` and Node would otherwise read it as CommonJS.
writeFileSync(join(OUT_DIR, "package.json"), JSON.stringify({ type: "module" }, null, 2) + "\n")

const bytes = statSync(OUT_FILE).size
console.log(`\nBundled ${OUT_FILE} (${(bytes / 1024).toFixed(0)} kB)`)

// Guard against the bundle silently swallowing the Next.js/React world: if that
// ever gets pulled in, the archive balloons and the server stops being portable.
const forbidden = Object.keys(result.metafile.inputs).filter((f) =>
  /node_modules\/(next|react|react-dom|@carbon)\//.test(f)
)
if (forbidden.length > 0) {
  throw new Error(
    `The bundle pulled in front-end packages, which it must not:\n  ${forbidden.slice(0, 10).join("\n  ")}`
  )
}

// ── 3. Smoke-test the output ───────────────────────────────────────────────
// The server must start, refuse to run without credentials, and say why. This
// catches a bundle that is syntactically fine but broken at module scope.
{
  const res = spawnSync(process.execPath, [OUT_FILE], {
    cwd: ROOT,
    encoding: "utf8",
    timeout: 30_000,
    // Deliberately empty credentials; inherit nothing that could satisfy them.
    env: { PATH: process.env.PATH, HOME: process.env.HOME, SKAT_LOG_LEVEL: "debug" },
  })
  const stderr = res.stderr ?? ""
  if (!stderr.includes("Missing required configuration")) {
    throw new Error(
      `Smoke test failed: expected a configuration error on stderr.\nexit=${res.status}\nstderr:\n${stderr}\nstdout:\n${res.stdout}`
    )
  }
  if ((res.stdout ?? "").trim() !== "") {
    throw new Error(`Smoke test failed: the server wrote to stdout before the protocol started:\n${res.stdout}`)
  }
  console.log("Startup check: refuses to run unconfigured, keeps stdout clean ✓\n")
}

// Then a real MCP conversation over stdio, in both tool-visibility modes.
run(process.execPath, ["scripts/smoke-mcpb.mjs"])
run(process.execPath, ["scripts/smoke-mcpb.mjs", "--read-only"])

// ── 4. Validate + pack ─────────────────────────────────────────────────────
run("npx", ["--yes", "@anthropic-ai/mcpb@latest", "validate", join(BUNDLE_DIR, "manifest.json")])

if (pack) {
  mkdirSync(DIST_DIR, { recursive: true })
  const out = join(DIST_DIR, `${manifest.name}-${manifest.version}.mcpb`)
  run("npx", ["--yes", "@anthropic-ai/mcpb@latest", "pack", BUNDLE_DIR, out])

  // Trust the archive, not the .mcpbignore: read back what actually shipped.
  const entries = listZipEntries(out)
  console.log(`\nArchive contains ${entries.length} files:`)
  for (const name of entries) console.log(`  ${name}`)

  const unwanted = entries.filter((name) => /\.(ts|tsx|map)$/.test(name) || name.startsWith("src/"))
  if (unwanted.length > 0) {
    throw new Error(`Source files leaked into the archive:\n  ${unwanted.join("\n  ")}`)
  }
  for (const required of ["manifest.json", manifest.icon ?? "icon.png", manifest.server.entry_point]) {
    if (!entries.includes(required)) {
      throw new Error(`The archive is missing ${required}`)
    }
  }

  console.log(`\nBundle ready: ${out}`)
} else {
  console.log("\nSkipped packing (--no-pack).")
}

/**
 * File names in a zip, read from its central directory. Avoids depending on an
 * `unzip` binary being present.
 */
function listZipEntries(path) {
  const buf = readFileSync(path)
  const SIG = 0x02014b50 // central directory file header
  const names = []
  for (let i = 0; i <= buf.length - 46; i++) {
    if (buf.readUInt32LE(i) !== SIG) continue
    const nameLength = buf.readUInt16LE(i + 28)
    const extraLength = buf.readUInt16LE(i + 30)
    const commentLength = buf.readUInt16LE(i + 32)
    names.push(buf.toString("utf8", i + 46, i + 46 + nameLength))
    i += 46 + nameLength + extraLength + commentLength - 1
  }
  return names
}
